env: "dev"
storage_path: "host=127.0.0.1 port=5432 user=postgres password=postgres dbname=poker sslmode=disable"
http_server:
  address: "0.0.0.0:33090"
  timeout: 4s
  idle_timeout: 30s
  user: "myuser"
  password: "mypass"